# Tags: nanoserver-1809-amd64, nanoserver-1809-amd64-1503230
FROM mcr.microsoft.com/dotnet-buildtools/image-builder:nanoserver-1809-amd64
FROM mcr.microsoft.com/dotnet-buildtools/image-builder:nanoserver-1809-amd64-1503230
