# Tags: nanoserver-2004-amd64, nanoserver-2004-amd64-1461479
FROM mcr.microsoft.com/dotnet-buildtools/image-builder:nanoserver-2004-amd64
FROM mcr.microsoft.com/dotnet-buildtools/image-builder:nanoserver-2004-amd64-1461479
