# Tags: windowsservercore-ltsc2016-amd64, windowsservercore-ltsc2016-amd64-1503230
FROM mcr.microsoft.com/dotnet-buildtools/image-builder:windowsservercore-ltsc2016-amd64
FROM mcr.microsoft.com/dotnet-buildtools/image-builder:windowsservercore-ltsc2016-amd64-1503230
