# Tags: nanoserver-ltsc2022-amd64, nanoserver-ltsc2022-amd64-1503230
FROM mcr.microsoft.com/dotnet-buildtools/image-builder:nanoserver-ltsc2022-amd64
FROM mcr.microsoft.com/dotnet-buildtools/image-builder:nanoserver-ltsc2022-amd64-1503230
